import Head from 'next/head'
import React, { ReactElement } from 'react'
import styles from '../styles/global.module.scss'

type Props = {
  title?: string
  children: React.ReactNode
}

export const Container: React.FC<Props> = ({ title = '', children }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>
          {`noripi10's blog `}
          {title}
        </title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {children}
      <footer className={styles.footer}>
        <div>Copyright @ {new Date().getFullYear} noripi10 All Rights Reserved.</div>
      </footer>
    </div>
  )
}
