import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { client } from '../libs/client';

import { Header } from '../components/Header';

import styles from '../styles/global.module.scss';

export default function Home(props) {
	const { blogs } = props;
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
			<main className={styles.main}>
				<div>
					<ul>
						{blogs.map((blog) => (
							<li key={blog.id}>
								<Link href={`/blog/${blog.id}`}>
									<a>{blog.title}</a>
								</Link>
							</li>
						))}
					</ul>
				</div>
			</main>

			<footer className={styles.footer}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Powered by{' '}
					<span className={styles.logo}>
						<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
					</span>
				</a>
			</footer>
		</div>
	);
}

export const getStaticProps = async () => {
	const data = await client.get({ endpoint: 'techblog' });

	// 作成日でバブルソート
	const blogs = data.contents.sort((a, b) => {
		const aDate = new Date(a.createdAt);
		const bDate = new Date(b.createdAt);
		if (aDate > bDate) {
			return 1;
		} else if (aDate < bDate) {
			return -1;
		} else if (aDate === bDate) {
			return 0;
		}
	});

	return {
		props: {
			blogs,
		},
	};
};
